export {default as Header } from './Header/Header'
export {default as NavBar } from './NavBar/NavBar'
export {default as Main } from './Main/Main'
export {default as Movie } from './Movie/Movie'
export {default as MoviesContainer } from './MoviesContainer/MoviesContainer'
export {default as Player } from './Player/Player'
 export {default as Authentication } from './Authentication/Authentication'
// export {default as Header } from './Header/Header'
// export {default as Header } from './Header/Header'