
const constants ={
    TOP_RATED: "TOP_RATED",
    RECCOMENTED :"RECCOMENTED",
    TRENDING: "TRENDING",
    HORROR: "HORROR",
    ACTION: "ACTION",
    ROMANCE: "ROMANCE",
    DOCUMENTARIES: "DOCUMENTARIES",
    SET_USER: "SET_USER"
}
export default constants;